### ISSUE TITLE
Trancar transações até a sincronização estar completa/ estar online

### ISSUE THREAD

**Issue by FredericoVillani** [niobio-cash/niobio-wallet#27]

**Comment by FredericoVillani** [comment]
Adicionar e testar ao arquivo SendFrame "void SendFrame::synchronizationProgressUpdated(quint32 _current, quint32 _total) {
  if (_total - _current > MAXIMUM_UNSYNCED_BLOCKS_WHEN_SEND_AVAILABLE) {
    m_glassFrame->install(this);
    m_glassFrame->updateSynchronizationState(_current, _total);
  }
}

void SendFrame::synchronizationCompleted() {
  m_glassFrame->remove();
} "

**Comment by vitorgamer58** [comment]
realmente, já que está sendo possível fazer transações antes da sincronização podendo acarretar bugs
