### ISSUE TITLE
Pool list

### ISSUE THREAD

**Issue by Deltacrypto** [niobio-cash/niobio-wallet#32]
hello i have compiled your gui wallet for another coin, but i cant remove nbr pools and nodes from gui wallet >> pool mining section, thanks.

**Comment by vitorgamer58** [comment]
deve ter algum lugar no código em que é possível configurar a lista de pools, mas os nodes... bom, esses já estão na configuração do Daemon, é melhor você usar o daemon da sua moeda cryptonote neste caso.
