### ISSUE TITLE
Carteira Dúvidas

### ISSUE THREAD

**Issue by PauloBoaventura** [niobio-cash/niobio-wallet#37]
Ola pessoas... 
Bom tenho algumas dúvidas... Uso o Linux (Ubuntu) e queria saber como ter o número da carteira.
E como fazer para transferir tanto para dentro da carteira, como para outra carteira se for o caso... 

Abraços!

**Comment by FredericoVillani** [comment]
Boa noite, você está usando a versão prompt de comando?

**Comment by helder-garcia** [comment]
Fechando a issue por falta de comunicação da parte interessada.
