### ISSUE TITLE
carteira travada no 93500

### ISSUE THREAD

**Issue by CassiusPanice** [niobio-cash/niobio-wallet#38]
minha carteira versão 1.3.1 travou dia 02/06 no bloco 93500, ja baixei carteiras mais recente 1.3.3 , mas ela não abre,   baixei blockain colei na pasta niobio e mesmo sincronizou tudo do zero e mesmo assim trava no 93500, alguem pode me ajudar por favor ?

**Comment by FredericoVillani** [comment]
você realizou o download dos 8 arquivos .zip e os descompactou?

**Comment by aloisiodias** [comment]
Estou com o mesmo problema. Baixei os 8 arquivos Zip da blockchain e dá erro: "blockchain-height-91030.z01: o arquivo está corrompido". Usei 2 pcs diferentes, baixei 3 vezes em cada PC. O arquivo está com problemas.

**Comment by aloisiodias** [comment]
Alguma dica?

**Comment by CassiusPanice** [comment]
sim os 8 e coloquei na pasta %appdata% niobio é ali mesmo ?

**Comment by FredericoVillani** [comment]
Isso... %appdata%/niobio ... Após descompactar os 8 feche e abra a carteira novamente... Também pode apagar o arquivo p2pstate.bin... se continuar o erro por favor avisem aqui

**Comment by CassiusPanice** [comment]
na verdade conferi agora tinha feito apenas 7 que estão numerados acredito que o 8 é o blockchain-height-91030 correto ? acabei de faze-lo e coloquei na pasta niobio pediu para substituir, e agora a sincronização voltou para 91030 e esta tentando sincronizar ...vou aguardar e depois respondo se deu certo
desde ja muito obrigado Frederico

**Comment by FredericoVillani** [comment]
Isso... esse é o mais importante pois é o primeiro para o encadeamento dos .zip
Qualquer novidade informe...
Estamos aqui pra ajudar!

**Comment by CassiusPanice** [comment]
Bom dia, como falei ontem coloquei o 8º arquivo que faltava e deixei
sincronizando, e mesmo assim para no 93500 porém não tinha apagado a pasta
que comentou, agora de manha apaguei o  p2pstate.bin fechei a carteira  e
esta sincronizando dinovo , mas ja esta parado no 93500/112024  acredito
que assim vai ficar, outra coisa é que estou usando a carteira 1.3.1,
baixei a 1.3.2 que tb trava no mesmo ponto ... e a 1.3.3 ela começa a abrir
e fecha em seguida , não abre
não sei se  a versão da carteira influi nisso, desde já agradeço e aguardo


<http://meccal.com.br/> <http://meccal.com.br/>

<http://meccal.com.br/> <http://meccal.com.br/> <http://meccal.com.br/>
<http://meccal.com.br/>[image:
http://www.klynk.com.br/assinaturas/meccal/logo1.png]
<http://meccal.com.br/> <http://meccal.com.br/>

<http://meccal.com.br/>[image:
http://www.klynk.com.br/assinaturas/meccal/logo2.png]
<http://meccal.com.br/>

*Cassius Panice*

*Depto. Engenharia*




*engenharia@meccal.com.br <%20financeiro@meccal.com.br>Av. Lucio Luciano,
2-33Bauru/SP(14) 3201-1522*


<http://www.facebook.com/meccalmaquinas>
<http://www.linkedin.com/company/3083255?goback=%2Efcs_GLHD_meccal_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>



2018-07-25 19:12 GMT-03:00 FredericoVillani <notifications@github.com>:

**Comment by FredericoVillani** [comment]
Boa noite! A versão influi sim, sendo a 1.3.3 a responsável por fazer a passagem do softfork que ocorreu próximo a altura 93500. Ao utilizar versões anteriores da carteira, você vai sempre travar no mesmo ponto (93500). Repita o procedimento de substituir os arquivos na pasta %appdata%/niobio , porém, desta vez, abra a carteira 1.3.3 em seguida.

**Comment by CassiusPanice** [comment]
deu certo, agora estou com outro problema veja se pode me ajudar

sempre usei esta claymore para Nvidia >

NsGpuCNMiner.exe -o stratum+tcp://us-nbr.4miner.me:3334 -u CARTEIRA
carteira x -allpools 1

e este para RADEON
NsGpuCNMiner.exe -o stratum+tcp://us-nbr.4miner.me:3334 -u  carteira -allpools
1

de alguns dias para k ambos aparecem erros DIZENDO que meu IP foi BANIDO e
outros erros

ja tentei todas as portas que o 4miner disponibiliza e nada , e tb tentei
servidor e portas do proprio site da niobio e tb da erro

oque posso fazer ?

desculpe mas sou meio leigo,



<http://meccal.com.br/> <http://meccal.com.br/>

<http://meccal.com.br/> <http://meccal.com.br/> <http://meccal.com.br/>
<http://meccal.com.br/>[image:
http://www.klynk.com.br/assinaturas/meccal/logo1.png]
<http://meccal.com.br/> <http://meccal.com.br/>

<http://meccal.com.br/>[image:
http://www.klynk.com.br/assinaturas/meccal/logo2.png]
<http://meccal.com.br/>

*Cassius Panice*

*Depto. Engenharia*




*engenharia@meccal.com.br <%20financeiro@meccal.com.br>Av. Lucio Luciano,
2-33Bauru/SP(14) 3201-1522*


<http://www.facebook.com/meccalmaquinas>
<http://www.linkedin.com/company/3083255?goback=%2Efcs_GLHD_meccal_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>



Em 27 de julho de 2018 07:25, Cassius Panice - Meccal <cassius@meccal.com.br

**Comment by helder-garcia** [comment]
Cassius, vou fechar essa issue já que ela foi resolvida. Outro problema relacionados a carteira devem ser reportados em uma nova issue. Para o problema com mineração na pool, você deve entrar em contato com o provedor do serviço. Na página deles tem o telegram http://nbr.4miner.me
