### ISSUE TITLE
Carteira versão v1.3.6 linux , está resetando a database "blocks.dat" aleatoriamente.

### ISSUE THREAD

**Issue by zezaocapoeira** [niobio-cash/niobio-wallet#43]
Olá.

A sincronização da carteira versão v1.3.6 linux , está resetando a database **blocks.dat**  aconteceu pela segunda vez essa semana, (**29 de novembro de 2018** ) .

Vou deixar o log da wallet  depois do último acontecimento(**29 de novembro de 2018** ):
[niobiowallet.log.gz](https://github.com/niobio-cash/niobio-wallet/files/2630653/niobiowallet.log.gz)

Imagem dos arquivos correspondentes depois da sincronização travar:
![captura de tela_2018-11-29_17-59-42](https://user-images.githubusercontent.com/13563840/49248092-138d3a00-f400-11e8-9462-c6dd540dca9d.png)

Refiz o download do blockchain-height da página https://github.com/niobio-cash/niobio-wallet/releases/tag/v1.3.5.

![captura de tela_2018-11-29_18-04-52](https://user-images.githubusercontent.com/13563840/49248364-acbc5080-f400-11e8-9a06-956d700a5533.png)

E sobrescrevi os arquivos referentes : 
![captura de tela_2018-11-29_18-04-03](https://user-images.githubusercontent.com/13563840/49248465-e7be8400-f400-11e8-8750-533a0c77c338.png)

Agora estou fazendo a ressincronização da carteira novamente.

O principal problema é o reset do arquivo database **blocks.dat** , que acontece aleatoriamente.

Obrigado pela atenção.

**Comment by helder-garcia** [comment]
Por favor, pode detalhar mais o que acontece nesse reset? O arquivo zera em tamanho? O contador de blocos no sincronismo volta para algum bloco específico?

**Comment by zezaocapoeira** [comment]
> Por favor, pode detalhar mais o que acontece nesse reset? O arquivo zera em tamanho? O contador de blocos no sincronismo volta para algum bloco específico?

Olá.

Nas vezes que aconteceu isso, a carteira ficava congelava, o único jeito de fechar era matando o processo via terminal.

Depois disso a carteira não iniciava de forma alguma.

No arquivo **niobio.wallet.log.gz** na linha número **6826** começa a sincronizar e depois trava.

Na linha número **6937** é o momento que adicionei os arquivos database que baixei, depois disso a carteira abriu e começou a sincronizar novamente.

O interessante é que após finalizar a sincronização para o bloco atual, o arquivo **blocks.dat** teve seu tamanho reduzido, de **4gb** para aproximadamente **2,5gb** .

OBS:

Isso pode ter ocorrido quando o limite operacional do arquivo *blockscache.dat* atingiu o máximo da capacidade ou pelo *hard fork no bloco 153600* ?

Hoje ,04 de dezembro de 2018, está rodando normal.

O arquivo *niobio.wallet.log.gz* está compactado em *gzip*.

Obrigado pela atenção.

**Comment by FredericoVillani** [comment]
Fecharei o issue por ter sido resolvido
